name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install ghpages
        run: npm install -g angular-cli-ghpages

      - name: Create regali.json file
        run: echo '${{ secrets.REGALI_JSON }}' > src/app/_files/regali.json

      - name: Build the project
        run: ng build --configuration production --base-href https://The-Sunny-Side/babbo-segreto/

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd dist
          git init
          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/The-Sunny-Side/babbo-segreto.git
          git checkout -b gh-pages
          echo '' > .nojekyll
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
